services:
  - type: web
    name: portfolio-vlad
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate && python manage.py createsu"
    startCommand: "gunicorn core.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_EMAIL
        value: admin@example.com
      - key: ADMIN_PASSWORD
        generateValue: true
    autoDeploy: true

databases:
  - name: portfolio-db
    databaseName: portfolio
    user: portfolio
    region: frankfurt
    plan: free